apiVersion: v1
kind: Pod
metadata:
  name: pong
  labels:
    name: pong
    project: ping-pong
    version: "1"
spec:
  containers:
  - image: rhuss/pong:2
    name: pong
    ports:
    - containerPort: 8080
