apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
    name: ping
    project: ping-pong
    version: "1"
  name: ping
spec:
  replicas: 1
  selector:
    name: ping
    project: ping-pong
    version: "1"
  template:
    metadata:
      labels:
        name: ping
        project: ping-pong
        version: "1"
        uses: pong
    spec:
      containers:
      - image: "rhuss/jax2016-ping:1"
        name: ping
        env:
        - name: STRENGTH
          value: "5"
      # For demo:
      terminationGracePeriodSeconds: 1
